services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - app-network
    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: 'broker,controller'

      KAFKA_LISTENERS: 'CONTROLLER://:9093,PLAINTEXT://:29092,PLAINTEXT_HOST://0.0.0.0:9092'

      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'

      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  kafka-topic-creator:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - kafka
      networks:
        - app-network

      command: >
        bash -c "
          cub kafka-ready -b kafka:29092 1 20 &&
          kafka-topics --create --if-not-exists --topic my-first-topic \
          --bootstrap-server kafka:29092 \
          --partitions 1 \
          --replication-factor 1
        "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "18090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - app-network

  director-service:
    build:
      context: .
      dockerfile: director_service/Dockerfile
    container_name: director-service
    ports:
      - "8030:8030"
      - "8092:8092"
    networks:
      - app-network
    environment:
      - GRPC_PORT=8030
      - HTTP_PORT=8092
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=my-first-topic
      - LOG_LEVEL=info
      - LOG_FORMAT=tskv
    depends_on:
      - kafka
      - kafka-topic-creator

  admin-panel:
    build:
      context: .
      dockerfile: AdminPanel/Dockerfile
    container_name: admin-panel
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - DEBUG=False
      - DIRECTOR_GRPC_ADDRESS=director-service:8030
      - ALLOWED_HOSTS=localhost,127.0.0.1,admin-panel
    volumes:
      - ./AdminPanel/db.sqlite3:/app/db.sqlite3
      - ./AdminPanel/staticfiles:/app/staticfiles
    depends_on:
      - director-service

  api-gateway:
    build:
      context: .
      dockerfile: ApiGateWay/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - GRPC_SERVICE_ADDRESS=director-service:8030
    depends_on:
      - director-service

networks:
  app-network:
    driver: bridge