config_vars: configs/config_vars.yaml

components_manager:
    coro_pool:
        initial_size: $coro_pool_initial_size
        max_size: $coro_pool_max_size
        stack_size: $coro_pool_stack_size
        stack_usage_monitor_enabled: $coro_pool_monitor_enabled
        
    components:
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $log_level
                    overflow_behavior: discard
                    format: $log_format

        secdist:
            provider: default-secdist-provider
            
        default-secdist-provider:
            config: configs/secdist.json
            missing-ok: true

        kafka-producer:
            delivery_timeout: 5s
            queue_buffering_max: 1s
            enable_idempotence: true
            security_protocol: PLAINTEXT
            operation_log_level: warning
            rd_kafka_custom_options:
                bootstrap.servers: $kafka_bootstrap_servers

        director-producer:
            task-processor: director-producer-task-processor
            topic: $kafka_topic

        grpc-server:
            port: $grpc_port

        grpc-server-middlewares-pipeline:
            middlewares: {}

        profile-receiver-service:
            task-processor: main-task-processor
            profile-prefix: profile

        transaction-receiver-service:
            task-processor: main-task-processor
            transaction-prefix: transaction

        server:
            listener:
                port: $http_port
                task_processor: main-task-processor

    task_processors:
        fs-task-processor:
            worker_threads: $fs_workers
            thread_name: fs-worker
            
        grpc-blocking-task-processor:
            worker_threads: $grpc_workers
            thread_name: grpc-worker

        producer-task-processor:
            worker_threads: $producer_workers
            thread_name: producer

        main-task-processor:
            worker_threads: $main_workers
            thread_name: main-worker

        director-producer-task-processor:
            worker_threads: $director_workers
            thread_name: director