components_manager:
    components:
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: info
                    overflow_behavior: discard

        grpc-server:
            port: 8030

        grpc-server-middlewares-pipeline:
            middlewares: {}

        profile-receiver-service:
            task-processor: main-task-processor
            profile-prefix: profile

        transaction-receiver-service:
            task-processor: main-task-processor
            transaction-prefix: transaction

        server:
            listener:
                port: 8092
                task_processor: main-task-processor

    task_processors:
        fs-task-processor:
            worker_threads: 2
            thread_name: fs-worker
            
        grpc-blocking-task-processor:
            worker_threads: 2
            thread_name: grpc-worker

        main-task-processor:
            worker_threads: 8
            thread_name: main-worker