components_manager:
    coro_pool:
        initial_size: 500
        max_size: 1000
        stack_size: 262144
        stack_usage_monitor_enabled: false
        
    components:
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $LOG_LEVEL
                    level#fallback: info
                    overflow_behavior: discard
                    format: $LOG_FORMAT
                    format#fallback: raw

        secdist:
            provider: default-secdist-provider
            
        default-secdist-provider:
            config: configs/secdist.json
            missing-ok: true

        kafka-producer:
            delivery_timeout: 5s
            queue_buffering_max: 1s
            enable_idempotence: true
            security_protocol: PLAINTEXT
            operation_log_level: warning
            rd_kafka_custom_options:
                bootstrap.servers: $KAFKA_BOOTSTRAP_SERVERS
                bootstrap.servers#fallback: kafka:29092

        director-producer:
            task-processor: director-producer-task-processor
            topic: $KAFKA_TOPIC
            topic#fallback: "Request"

        grpc-server:
            port: $GRPC_PORT
            port#fallback: 8030

        grpc-server-middlewares-pipeline:
            middlewares: {}

        profile-receiver-service:
            task-processor: main-task-processor
            profile-prefix: profile

        transaction-receiver-service:
            task-processor: main-task-processor
            transaction-prefix: transaction

        server:
            listener:
                port: $HTTP_PORT
                port#fallback: 8092
                task_processor: main-task-processor

    task_processors:
        fs-task-processor:
            worker_threads: $FS_WORKER_THREADS
            worker_threads#fallback: 2
            thread_name: fs-worker
            
        grpc-blocking-task-processor:
            worker_threads: $GRPC_WORKER_THREADS
            worker_threads#fallback: 2
            thread_name: grpc-worker

        producer-task-processor:
            worker_threads: $PRODUCER_WORKER_THREADS
            worker_threads#fallback: 2
            thread_name: producer

        main-task-processor:
            worker_threads: $MAIN_WORKER_THREADS
            worker_threads#fallback: 8
            thread_name: main-worker

        director-producer-task-processor:
            worker_threads: $DIRECTOR_WORKER_THREADS
            worker_threads#fallback: 8
            thread_name: director