apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    orgId: 1
    access: proxy
    url: http://loki:3100
    basicAuth: false

  - name: PostgreSQL
    type: postgres
    uid: postgres
    orgId: 1
    access: proxy
    url: postgres:5432
    database: it_cup_onecode
    user: postgres
    basicAuth: false
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    secureJsonData:
      password: postgres
